name: Add Approvers to Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options: ['dev', 'pre', 'pro']
        default: 'dev'
      approver:
        description: 'Username of the approver'
        required: true
        default: 'approver_username'

jobs:
  add-approvers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add Approvers to Environments
        env:
          ORGANIZATION: ${{ vars.ORGANIZATION }}
          ENVIRONMENT: ${{ inputs.environment }}
          APPROVER: ${{ inputs.approver }}
        run: |
          cat repos.txt
          while read -r line;

            ENV_ID=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
              "https://api.github.com/repos/$ORGANIZATION/$line/environments" | jq -r ".environments[] | select(.name==\"$ENVIRONMENT\") | .id")

            if [ -z "$ENV_ID" ]; then
              echo "Environment $ENVIRONMENT not found in repository $line"
              continue
            fi

            curl -s -X PUT -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repositories/$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" https://api.github.com/repos/$ORGANIZATION/$line | jq -r '.id')/environments/$ENVIRONMENT/required_reviewers" \
              -d "{\"users\":[\"$APPROVER\"]}"

            echo "Approver $APPROVER added to environment $ENVIRONMENT in repository $line"

          done < repos.txt
