---
name: Loop changing repo
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to automate'
        type: choice
        options: ['development', 'certification']

jobs:
  loop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print ls
      run: ls
      
    - name: Read file
      run: |
        git config --global user.name "DevOps Automatism"
        git config --global user.email devops-automatism@santanderglobaltech.com

        while read -r line;
        do
          git clone https://username:${{ secrets.GH_PAT }}@github.com/$line.git
          repo_name=$(basename "$line" .git)
          cd $repo_name
          git checkout ${{ inputs.branch }}

          cp ./../update_deploy_main.py .

          # Ejecutar el script Python
          python3 update_deploy_main.py

          # Eliminar el script Python después de la ejecución
          rm update_deploy_main.py

          if ! git diff --quiet; then
            echo "$line" >> ../version-update.file
            git add .github/workflows/deploy-main.yml
            git commit -m "Change workflow deploy-main"
            git push
          else
            echo "$line" >> ../not-version-update.file
          fi
          cd ..
          rm -rf "$repo_name"
        done < ${{ inputs.branch }}.file

    - name: Print Updated Repos
      run: cat version-update.file

    - name: Print Not Updated Repos
      run: cat not-version-update.file
